version: 2.0
defaults: &default_job
  working_directory: ~/repo

  docker:
    - image: circleci/ruby:2.4-node-browsers

  steps:
    - checkout

    # - type: cache-restore
    #   name: Restore bundle cache
    #   key: pwush-{{ checksum "Gemfile.lock" }}

    - run:
        name: install dependencies
        command: |
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    # - type: cache-save
    #   name: Store bundle cache
    #   key: pwush-{{ checksum "Gemfile.lock" }}
    #   paths:
    #     - vendor/bundle

    - run:
        name: Download cc-test-reporter
        command: |
          mkdir -p tmp/
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
          chmod +x ./tmp/cc-test-reporter

    - run:
        name: Run tests
        command: |
          bundle exec rake
          ./tmp/cc-test-reporter format-coverage -t simplecov -o tmp/codeclimate.json

    - run:
        name: Upload coverage results to Code Climate
        command: |
          ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.json -r ce337e25b76b0c3048abfdb2d5aa6d3e87cc8540d90f0029ef7416683814732e

jobs:
  ruby-2.4:
    <<: *default_job
    docker:
      - image: circleci/ruby:2.4-node-browsers
  ruby-2.5:
    <<: *default_job
    docker:
      - image: circleci/ruby:2.5-node-browsers
  ruby-2.6:
    <<: *default_job
    docker:
      - image: circleci/ruby:2.6-node-browsers

workflows:
  version: 2
  multiple-rubies:
    jobs:
      - ruby-2.4
      - ruby-2.5
      - ruby-2.6
